$content = Get-Content 'C:\Users\walte\Desktop\fantacalcio-sim-pack-v2\fantacalcio-sim\db\seeds\populate_real_players_SERIEA2025_26_complete.sql' -Raw
$content = $content -replace 'Cremonese', 'CRE'
$content = $content -replace 'Pisa', 'PIS'  
$content = $content -replace "'Roma'", "'ROMA'"
$content = $content -replace "'Milan'", "'MILAN'"
$content = $content -replace "'Inter'", "'INTER'"
$content = $content -replace "'Napoli'", "'NAPOLI'"
$content = $content -replace "'Juventus'", "'JUVENTUS'"
$content = $content -replace "'Lazio'", "'LAZIO'"
$content = $content -replace "'Atalanta'", "'ATALANTA'"
$content = $content -replace "'Bologna'", "'BOLOGNA'"
$content = $content -replace "'Cagliari'", "'CAGLIARI'"
$content = $content -replace "'Como'", "'COMO'"
$content = $content -replace "'Fiorentina'", "'FIORENTINA'"
$content = $content -replace "'Genoa'", "'GENOA'"
$content = $content -replace 'Hellas Verona', 'HELLAS VERONA'
$content = $content -replace "'Lecce'", "'LECCE'"
$content = $content -replace "'Parma'", "'PARMA'"
$content = $content -replace "'Sassuolo'", "'SASSUOLO'"
$content = $content -replace "'Torino'", "'TORINO'"
$content = $content -replace "'Udinese'", "'UDINESE'"
$content | Set-Content 'C:\Users\walte\Desktop\fantacalcio-sim-pack-v2\fantacalcio-sim\db\seeds\populate_real_players_SERIEA2025_26_complete.sql'